### ISSUE TITLE
WinVer1909 not working

### ISSUE THREAD

**Issue by 7q10** [Shivter14/SysShivt-tools#1]
Not working on Windows 10 ver 1909
Když chcu otevřít sysshivt tak prej že tato appka nemuze bezen na vasem kompu
Zkusil jsem BAT konvertovat do UTF-8 bez BOM a nejde to

**Comment by Shivter14** [comment]
Ahoj, jakou verzi SysShivt tools si použil?

**Comment by 7q10** [comment]
Už je to v pohodě když vyšla nová verze

**Comment by Shivter14** [comment]
ok
